-- posts 테이블 생성
CREATE TABLE posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category TEXT NOT NULL,
  title TEXT NOT NULL,
  preview TEXT NOT NULL,
  content TEXT NOT NULL,
  author TEXT NOT NULL,
  likes INT DEFAULT 0,
  comments INT DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- RLS (Row Level Security) 설정 (모두가 읽고 쓸 수 있도록 설정)
ALTER TABLE posts ENABLE ROW LEVEL SECURITY;

-- Select 정책: 모든 사용자가 읽을 수 있음
CREATE POLICY "Public profiles are viewable by everyone." 
ON posts FOR SELECT 
USING ( true );

-- Insert 정책: 모든 사용자가 글을 쓸 수 있음 (임시)
CREATE POLICY "Users can insert their own posts." 
ON posts FOR INSERT 
WITH CHECK ( true );

-- Update 정책: 로그인한 사용자가 자신의 게시물만 수정할 수 있음
CREATE POLICY "Users can update their own posts."
ON posts FOR UPDATE
USING ( auth.uid() = user_id );

-- Delete 정책: 로그인한 사용자가 자신의 게시물만 삭제할 수 있음
CREATE POLICY "Users can delete their own posts."
ON posts FOR DELETE
USING ( auth.uid() = user_id );

-- 초기 임시 데이터 삽입
INSERT INTO posts (category, title, preview, content, author, likes, comments)
VALUES 
  ('free', 'Next.js로 사이드 프로젝트 하실 분!', '프론트 1, 백 1 구합니다. 기획은 어느정도 나와있어요.', '프론트 1, 백 1 구합니다. 기획은 어느정도 나와있어요. 같이 하실 분 구해요!', '익명', 12, 4),
  ('free', '오늘 학생식당 메뉴 별로인가요?', '줄이 유독 짧은 것 같은데 기분탓인가', '줄이 유독 짧은 것 같은데 기분탓인가요?', '익명', 2, 1),
  ('free', '교양꿀강 추천해주세요!!', '팀플 없고 시험 쉬운걸로 부탁드립니다 ㅎㅎ', '팀플 없고 시험 쉬운걸로 부탁드립니다 ㅎㅎ 꿀강 추천좀!', '익명', 18, 9),
  ('skill', '스프링 백엔드와 리액트 교환하실 분 (주 1회)', '주 1회 디스코드에서 만나서 스터디식으로 교환해요', '스프링 백엔드와 리액트 교환하실 분 구합니다. 주 1회 정도면 좋을 것 같아요.', '김토스', 5, 2),
  ('contest', '이번 주말 해커톤 프론트 1명 급구합니다 🔥', 'React 잘하시는 분 연락주세요', '이번 주말 열리는 해커톤 프론트엔드 1명 급구합니다! 연락주세요.', '익명', 10, 3),
  ('study', 'CS 기술면접 스터디원 모집 (2/4)', '매주 일요일 저녁 8시 비대면', 'CS 기술면접 스터디원 모집합니다. 현재 2명이고 4명까지 모집할 계획입니다.', '면접왕', 7, 1);

-- --------------------------------------------------------
-- 프로필(profiles) 테이블 생성 (Supabase Auth 연동)
-- --------------------------------------------------------
CREATE TABLE profiles (
  id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  name TEXT NOT NULL,
  major TEXT,
  summary TEXT,
  skills JSONB DEFAULT '[]'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- RLS (Row Level Security) 설정
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;

-- Select 정책: 모든 사용자가 프로필을 볼 수 있음
CREATE POLICY "Public profiles are viewable by everyone." 
ON profiles FOR SELECT 
USING ( true );

-- Insert 정책: 로그인한 사용자만 자신의 프로필을 생성할 수 있음
CREATE POLICY "Users can insert their own profile." 
ON profiles FOR INSERT 
WITH CHECK ( auth.uid() = id );

-- Update 정책: 로그인한 사용자만 자신의 프로필을 수정할 수 있음
CREATE POLICY "Users can update own profile." 
ON profiles FOR UPDATE 
USING ( auth.uid() = id );

-- --------------------------------------------------------
-- 게시물(posts) 테이블 스키마 변경 (프로필 및 채팅 연동용)
-- --------------------------------------------------------
-- Supabase 대시보드의 SQL Editor에서 아래 구문을 추가로 실행해 주세요.
-- ALTER TABLE posts ADD COLUMN user_id UUID REFERENCES profiles(id) ON DELETE CASCADE;
-- ALTER TABLE posts ADD COLUMN is_anonymous BOOLEAN DEFAULT false;

-- --------------------------------------------------------
-- 메시지(messages) 테이블 생성 (실시간 채팅용)
-- --------------------------------------------------------
CREATE TABLE messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sender_id UUID REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
  receiver_id UUID REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
  post_id BIGINT REFERENCES posts(id) ON DELETE CASCADE,
  content TEXT NOT NULL,
  is_read BOOLEAN DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 기존에 messages 테이블을 만드셨다면 아래 ALTER 구문만 실행해주세요.
-- ALTER TABLE messages ADD COLUMN is_read BOOLEAN DEFAULT false;
-- UPDATE messages SET is_read = true WHERE is_read IS NULL;

-- RLS (Row Level Security) 설정
ALTER TABLE messages ENABLE ROW LEVEL SECURITY;

-- Select 정책: 사용자가 보냈거나 받은 메시지만 읽을 수 있음
CREATE POLICY "Users can read their own messages." 
ON messages FOR SELECT 
USING ( auth.uid() = sender_id OR auth.uid() = receiver_id );

-- Insert 정책: 로그인한 사용자가 발신자인 경우만 메시지를 보낼 수 있음
CREATE POLICY "Users can insert messages as sender." 
ON messages FOR INSERT 
WITH CHECK ( auth.uid() = sender_id );

-- Update 정책: 수신자만 메시지를 읽음 처리할 수 있음
CREATE POLICY "Users can update received messages." 
ON messages FOR UPDATE 
USING ( auth.uid() = receiver_id );

-- --------------------------------------------------------
-- 실시간(Realtime) 기능 활성화
-- --------------------------------------------------------
-- messages 테이블의 변경사항(새 메시지 등)을 클라이언트에서 실시간으로 받기 위해 필요합니다.
ALTER PUBLICATION supabase_realtime ADD TABLE messages;

-- --------------------------------------------------------
-- 리뷰(reviews) 테이블 생성 (스킬 교환 평가용)
-- --------------------------------------------------------
CREATE TABLE reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reviewer_id UUID REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
  reviewee_id UUID REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
  post_id BIGINT REFERENCES posts(id) ON DELETE SET NULL,
  rating INT NOT NULL CHECK (rating >= 1 AND rating <= 5),
  tags JSONB DEFAULT '[]'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- RLS (Row Level Security) 설정
ALTER TABLE reviews ENABLE ROW LEVEL SECURITY;

-- Select 정책: 모든 사용자가 리뷰를 볼 수 있음
CREATE POLICY "Public reviews are viewable by everyone." 
ON reviews FOR SELECT 
USING ( true );

-- Insert 정책: 로그인한 사용자가 리뷰 작성자인 경우만 추가 가능  
CREATE POLICY "Users can insert their own reviews." 
ON reviews FOR INSERT 
WITH CHECK ( auth.uid() = reviewer_id );
